# -*- coding: utf-8 -*-
"""chroma_store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pxy-4Nv88mr6bTqcdW5mNZX0BerXkOqL

## chroma store
"""

from pathlib import Path

import chromadb
from chromadb.config import Settings

# -------------------------
# Configuration
# -------------------------
DB_PATH = Path("chroma_db")
COLLECTION_NAME = "egyptian_greek_myths"

# -------------------------
# Create Vector Store
# -------------------------
def create_vector_store():

    client = chromadb.PersistentClient(
        path=str(DB_PATH),
        settings=Settings(anonymized_telemetry=False),
    )

    try:
        client.delete_collection(COLLECTION_NAME)
    except:
        pass

    collection = client.create_collection(COLLECTION_NAME)

    collection.add(
        ids=[chunk["chunk_id"] for chunk in chunks],

        documents=[chunk["chunk_text"] for chunk in chunks],

        metadatas=[
            {
                "document_id": chunk["document_id"],
                "title": chunk["title"],
                "is_current": str(chunk["is_current"]),
            }
            for chunk in chunks
        ],

        embeddings=chunk_embeddings.tolist(),
    )

    print(f"Stored {collection.count()} chunks.")

    return collection


# -------------------------
# Run
# -------------------------
collection = create_vector_store()