# -*- coding: utf-8 -*-
"""Embedding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ujuxys9sAI18QvY41mvrFZnHM-OE0V2

## Embedding
"""

import numpy as np
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from chunking import build_chunks
from preprocessing import preprocess_for_bm25,preprocess_for_embeddingchunks 
chunks = build_chunks()

MODEL_NAME = "BAAI/bge-small-en-v1.5"
ALPHA = 0.7

# ---------------------------------
# BM25
# ---------------------------------
tokenized_chunks = [
    preprocess_for_bm25(chunk["chunk_text"]).split()
    for chunk in chunks
]

bm25 = BM25Okapi(tokenized_chunks)

# ---------------------------------
# Embedding Model
# ---------------------------------
print("Loading embedding model...")

model = SentenceTransformer(MODEL_NAME)

print("Encoding chunks...")

chunk_embeddings = model.encode(
    [
        preprocess_for_embedding(chunk["chunk_text"])
        for chunk in chunks
    ],
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True,
)

print(f"Total embeddings: {len(chunk_embeddings)}")


# ---------------------------------
# Normalize Scores
# ---------------------------------
def min_max_normalize(scores):

    scores = np.asarray(scores, dtype=float)

    if scores.max() == scores.min():
        return np.zeros_like(scores)

    return (scores - scores.min()) / (scores.max() - scores.min())


# ---------------------------------
# Hybrid Search
# ---------------------------------
def hybrid_search(query, k=3):

    bm25_query = preprocess_for_bm25(query)

    embedding_query = preprocess_for_embedding(query)

    # BM25
    bm25_scores = bm25.get_scores(
        bm25_query.split()
    )

    # Embedding
    query_embedding = model.encode(
        [embedding_query],
        convert_to_numpy=True,
        normalize_embeddings=True,
    )

    embedding_scores = cosine_similarity(
        query_embedding,
        chunk_embeddings
    ).flatten()

    # Hybrid Score
    hybrid_scores = (
        (1 - ALPHA) * min_max_normalize(bm25_scores)
        + ALPHA * min_max_normalize(embedding_scores)
    )

    ranking = np.argsort(hybrid_scores)[::-1][:k]

    results = []

    for idx in ranking:

        result = chunks[idx].copy()

        result["score"] = float(hybrid_scores[idx])

        results.append(result)

    return results
