# -*- coding: utf-8 -*-
"""Import& Dou.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmCun_aWnXWc-RR81nDFSTow5zPZQ6Nh

## Import & Documents
"""

import pandas as pd

FILE_PATH = "egyptian_greek_myths_filled.xlsx"

df = pd.read_excel(FILE_PATH)

documents = []

for _, row in df.iterrows():

    text = f"""
    Name: {row['Name']}
    Civilization: {row['Civilization']}
    Role: {row['Role']}
    Myth: {row['Myth']}
    Historically Accurate: {row['Historically Accurate?']}
    """

    documents.append(
        {
            "id": str(row["ID"]),
            "title": row["Name"],
            "is_current": True,
            "text": text.strip(),
        }
    )

if __name__ == "__main__":
    print(f"Loaded {len(documents)} documents.")
    print(documents[0])