# -*- coding: utf-8 -*-
"""Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBxPRfsFXQc9HudRbI0iLpu7--AJKHf5

#Model
"""

import streamlit as st
from openai import OpenAI

from retrieve import build_context
from prompting import build_prompt, SYSTEM_PROMPT


@st.cache_resource
def get_client():
    if "OPENROUTER_API_KEY" not in st.secrets:
        st.error(
            "OPENROUTER_API_KEY not found in Secrets. "
            "Add it under Manage app -> Settings -> Secrets."
        )
        st.stop()

    return OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=st.secrets["OPENROUTER_API_KEY"],
    )


def ask_model(question):
    client = get_client()

    context, sources = build_context(question)
    prompt = build_prompt(question, context)

    response = client.chat.completions.create(
        model="qwen/qwen-2.5-7b-instruct",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        temperature=0,
        top_p=0.1,
    )

    return response.choices[0].message.content, sources


if __name__ == "__main__":
    answer, sources = ask_model("Who tricked death twice?")
    print(answer)
