# -*- coding: utf-8 -*-
"""Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBxPRfsFXQc9HudRbI0iLpu7--AJKHf5

#Model
"""

from openai import OpenAI
import streamlit as st

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=st.secrets["OPENROUTER_API_KEY"]
)

question = "Who tricked death twice?"

context, _ = build_context(question)
prompt = build_prompt(question, context)

print("========== PROMPT ==========")
print(prompt)

response = client.chat.completions.create(
    model="qwen/qwen-2.5-7b-instruct",
    messages=[
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0,
    top_p=0.1,
)

print("\n========== MODEL RESPONSE ==========")
print(response.choices[0].message.content)

# ====================================================

question = "Who were the parents of Osiris?"

context, _ = build_context(question)
prompt = build_prompt(question, context)

print("========== PROMPT ==========")
print(prompt)

response = client.chat.completions.create(
    model="qwen/qwen-2.5-7b-instruct",
    messages=[
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0,
    top_p=0.1,
)

print("\n========== MODEL RESPONSE ==========")
print(response.choices[0].message.content)
