# -*- coding: utf-8 -*-
"""Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBxPRfsFXQc9HudRbI0iLpu7--AJKHf5

#Model
"""

import ollama

question = "Who tricked death twice?"

context, _ = build_context(question)

prompt = build_prompt(question, context)

print("========== PROMPT ==========")
print(prompt)

response = ollama.chat(
    model="qwen2.5:7b",
    messages=[
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    options={
        "temperature": 0,
        "top_p": 0.1,
    }
)

print("\n========== MODEL RESPONSE ==========")
print(response["message"]["content"])

question = "Who were the parents of Osiris?"

context, _ = build_context(question)

prompt = build_prompt(question, context)

print("========== PROMPT ==========")
print(prompt)

response = ollama.chat(
    model="qwen2.5:7b",
    messages=[
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    options={
        "temperature": 0,
        "top_p": 0.1,
    }
)

print("\n========== MODEL RESPONSE ==========")
print(response["message"]["content"])