# -*- coding: utf-8 -*-
"""retrieve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dAJzSYnTW4C5UC5pMg_o82pkpaV1WS5

## retrieve
"""

import re
import numpy as np
from rank_bm25 import BM25Okapi

from embedding import model
from chroma_store import collection
from chunking import chunks
from preprocessing import (
    preprocess_for_bm25,
    preprocess_for_embedding,
)
from import_dou import documents, character_aliases

# ---------------------------------
# Detect comparison questions
# ---------------------------------
def is_comparison_question(question):

    comparison_words = [
        "compare",
        "difference",
        "different",
        "similar",
        "similarities",
        "vs",
        "versus",
    ]

    question = question.lower()

    return any(word in question for word in comparison_words)


# ---------------------------------
# Find character names mentioned in the question
# ---------------------------------
def find_characters(question):

    names = []

    question = question.lower()

    for alias, real_name in character_aliases.items():
        question = question.replace(alias, real_name)

    for doc in documents:

        title = doc["title"].lower()

        if title in question:
            names.append(doc)
            continue

        clean_title = re.sub(r"\(.*?\)", "", title).strip()

        if clean_title in question:
            names.append(doc)

    return names


# ---------------------------------
# Build Context
# ---------------------------------
def build_context(question):

    results = hybrid_search(question, k=5)

    if len(results) == 0:
        return "", []

    selected_documents = []
    seen = set()

    # ---------------------------------
    # Add mentioned characters first
    # ---------------------------------
    if is_comparison_question(question):

        mentioned = find_characters(question)

        for doc in mentioned:

            if doc["id"] not in seen:

                selected_documents.append(doc)
                seen.add(doc["id"])

    # ---------------------------------
    # Complete with Hybrid Search results
    # ---------------------------------
    for row in results:

        if row["document_id"] in seen:
            continue

        if row["score"] < 0.50:
            continue

        seen.add(row["document_id"])

        for doc in documents:

            if doc["id"] == row["document_id"]:

                selected_documents.append(doc)
                break

        if len(selected_documents) == 5:
            break

    if len(selected_documents) == 0:
        return "", []

    # ---------------------------------
    # Build Context
    # ---------------------------------
    context_parts = []

    for i, doc in enumerate(selected_documents, start=1):

        context_parts.append(
            f"==============================\n"
            f"SOURCE {i}\n"
            f"==============================\n"
            f"Title: {doc['title']}\n\n"
            f"{doc['text']}\n"
        )

    context = "\n".join(context_parts)

    return context.strip(), selected_documents

# ---------------------------------
# Prepare BM25
# ---------------------------------

tokenized_chunks = [
    preprocess_for_bm25(chunk["chunk_text"]).split()
    for chunk in chunks
]

bm25 = BM25Okapi(tokenized_chunks)

# ---------------------------------
# Normalize Scores
# ---------------------------------

def min_max_normalize(scores):
    scores = np.asarray(scores, dtype=float)

    if len(scores) == 0:
        return scores

    if scores.max() == scores.min():
        return np.zeros_like(scores)

    return (scores - scores.min()) / (scores.max() - scores.min())# ---------------------------------
# Hybrid Search
# ---------------------------------

ALPHA = 0.7


def hybrid_search(question, k=5):

    # =============================
    # 1. Vector Search (Chroma)
    # =============================

    query_embedding = model.encode(
        [preprocess_for_embedding(question)],
        convert_to_numpy=True,
        normalize_embeddings=True
    )


    vector_results = collection.query(
        query_embeddings=query_embedding.tolist(),
        n_results=k
    )


    vector_scores = {}

    for chunk_id, distance in zip(
        vector_results["ids"][0],
        vector_results["distances"][0]
    ):

        vector_scores[chunk_id] = 1 - distance



    # =============================
    # 2. BM25 Search
    # =============================

    bm25_query = preprocess_for_bm25(question)

    bm25_scores = bm25.get_scores(
        bm25_query.split()
    )


    bm25_scores_norm = min_max_normalize(
        bm25_scores
    )


    bm25_results = {}

    for idx, score in enumerate(bm25_scores_norm):

        bm25_results[
            chunks[idx]["chunk_id"]
        ] = score



    # =============================
    # 3. Combine Scores
    # =============================

    all_ids = set(
        list(vector_scores.keys()) +
        list(bm25_results.keys())
    )


    final_results = []


    for chunk_id in all_ids:

        vector_score = vector_scores.get(
            chunk_id,
            0
        )

        bm25_score = bm25_results.get(
            chunk_id,
            0
        )


        final_score = (
            ALPHA * vector_score
            +
            (1 - ALPHA) * bm25_score
        )


        final_results.append(
            {
                "chunk_id": chunk_id,
                "score": float(final_score)
            }
        )


    # =============================
    # 4. Sort Results
    # =============================

    final_results = sorted(
        final_results,
        key=lambda x: x["score"],
        reverse=True
    )


    # =============================
    # 5. Add Chunk Data
    # =============================

    output = []

    for result in final_results[:k]:

        for chunk in chunks:

            if chunk["chunk_id"] == result["chunk_id"]:

                item = chunk.copy()
                item["score"] = result["score"]

                output.append(item)
                break


    return output
