# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129MlCzGv4zVUE9TOtKBWR48RKqrMQDtW
"""

pip install sentence-transformers

context, sources = build_context(
    "Tell me the complete myth of Osiris"
)

print(context)

context, _ = build_context("Tell me the myth of Sisyphus?")
print(context[:5000])